displayName: Traefik Plugin Headers
type: middleware
import: github.com/dclairac/traefik-plugin-headers
summary: Allow to set/unset/edit/append values of request/response header based on regexp rules


# Configuration data for your plugin.
# This is mandatory,
# and Traefik Pilot will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  Rules:
    - Rule:
      name: 'png header'
      regexp: '.png$'
      responseHeaders:
        X-Check-R1-set1:
          value: 'New Value'
          action: 'set'
        X-Check-R1-set2:
          value: 'New Value'
          action: 'set'
    - Rule:
      name: 'No Match Default'
      regexp: 'NO_MATCH'
      requestHeaders:
        X-Check-edit:
          value: 'Date=@DT_ADD#86400@'
          replace: 'Date=[^,]+'
          action: 'edit'
        X-Check-append:
          value: 'Added Value'
          action: 'append'
        X-Check-unset:
          action: 'unset'